services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: netcodehub/localapi:v2
    container_name: webapi
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ProductDbContext=Server=host.docker.internal;Database=ProductDb;User Id=sa;Password=root;Trusted_Connection=False;TrustServerCertificate=true
    networks:
      - my_network

networks:
  my_network:
    driver: bridge  
